version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'project_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      projeto_network:
            ipv4_address: 172.10.0.5  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
        projeto_network:
              ipv4_address: 172.10.0.3  
volumes:
  my-db:
    driver: local

networks:
  projeto_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.0.1